### ISSUE TITLE
test_all.sh broken on systems where /usr/bin/python is Python 3

### ISSUE THREAD

**Issue by autrilla** [shinglyu/servo-perf#11]
`python -m SimpleHTTPServer > /dev/null 2>&1 &` uses Python 3 on said systems, and `SimpleHTTPServer` does not exist there. I suggest we explicitly use `python2`, which should exist on all relatively recent distributions.

**Comment by autrilla** [comment]
The same goes for the line `virtualenv venv; source venv/bin/activate; pip install treeherder-client` in the README, it should be `virtualenv -p python2 venv; source venv/bin/activate; pip install treeherder-client`

**Comment by shinglyu** [comment]
Ya, we should explicitly use `python2`, I was working exclusively in `python2` but moved to a mix of `python2` + `python3` because I need the `timeout` in `subprocess` (only available in python 3.3+).

**Comment by shinglyu** [comment]
@autrilla If you have a local working copy, you can open a pull request directly. The PR into the main servo repo may take some time, so we should continue to work on this repo for now.

**Comment by shinglyu** [comment]
@autrilla FYI: I migrated `submit_to_perfherder.py` to python3. And now I merged everything back to the `master` branch and will work on it instead of the `stage` branch.
