### ISSUE TITLE
Submit Gecko perf data to Perfherder

### ISSUE THREAD

**Issue by shinglyu** [shinglyu/servo-perf#20]
@autrilla 
There are quite a few things we need to change for Gecko in `submit_to_perfherder.py`

* `project`: `mozilla-central` (i.e. Nightly)
* `product_name`
* The whole `revision` and `revisions` list need to be changed to Gecko's commit log, though I'm not sure how do we match that with the downloaded nightly version. We could probably just use the version number from `firefox --version` as a temporary placeholder, and omit the parts we don't know (like author)
* `artifacts -> `blog` -> `blog`job_details`

**Comment by shinglyu** [comment]
Wait, we should probably try changing the `prouduct_name` to `mozilla-central` but keep the project as `servo`. I'm not sure how that looks like on the UI, but I don't want our test results show up in Gecko's list, this may confuse Gecko people.

**Comment by shinglyu** [comment]
Ok, I tested it but it might not work. 

So I would suggest you create a minimal version first, then try to get all the correct mozilla central revision info later.

The minimal version should be as simple as 
1. Change the `artifacts` -> `blob` for `name:performance_data` -> `suites` -> `name` to `gecko.49.0a1.performance.timing.domComplete` (Change the version number based on `firefox --version`
2. Change the job symbol to `GPL` (`Gecko Page Load`) or similar

This should create a separate graph for easy comparison with Servo.

Our top priority is to generate some data to get people interested in the performance issue, so you don't need to make all the data perfect, just make sure the data is separable from the servo data.

**Comment by shinglyu** [comment]
@autrilla I have to get this done before I leave for London on 6/3, so I'm afraid I have to take this bug from you.

**Comment by shinglyu** [comment]
![selection_011](https://cloud.githubusercontent.com/assets/3250983/15644081/632f25ac-2683-11e6-984e-3d9f6a4185da.png)

Everything is still very hacky. We use project=`servo` and product=`servo` for Gecko tests, because we don't want to confuse Platform people. So the only way to distinguish is to see the test name `gecko.domComplete` v.s. `domComplete` (servo). Also Firefox needs some  manual setup before running, so we can only run on Stable channel, and the test result will be fixed on its release date (~mid May)

**Comment by shinglyu** [comment]
cc @metajack

**Comment by autrilla** [comment]
What do you mean Firefox needs some manual setup? As far as I know profiles
should work cross-version.

**Comment by shinglyu** [comment]
@autrilla Your profile works fine. But I don't know why the `xpinstall.signature.required` becomes `true` again. So I have to manually open it, disable add-on signing to make it work. Also if there are existing tabs (e.g. Firefox default homescreen), it will prevent the window from closing, so the runner had to wait for time test to timeout. We might have to change the omnijar to make it work.
